![alt text](example2.jpeg "Title")

In [1]:
import numpy as np

X = []
vals = [0,1]
for i in vals:
    for j in vals:
        for k in vals:
            X.append([i, j, k])
X.append([vals[0], vals[0], vals[0]])
X.append([vals[1], vals[1], vals[1]])
X.append([vals[1], vals[1], vals[1]])    
X = np.array(X)

Y3 = -6 * (1 - X[:, 2]) + 5 * (X[:, 2])
Y12 = 4 * (1 - X[:, 0]) * (1 - X[:, 1]) - 6 * X[:, 0] * (1 - X[:, 1]) \
    - 6 * (1 - X[:, 0]) * X[:, 1] + 3 * X[:, 0] * X[:, 1]
Y = Y3 + Y12

In [2]:
(Y3 * Y12).mean()

1.0

## Fit intercept.

In [3]:
f0 = np.mean(Y)
residual = Y - f0
f0

0.0

## Fit mains.

In [4]:
def fit_main(residual, idx):
    f = np.array([np.mean(residual[X[:, idx] == vals[i]]) for i in range(len(vals))])
    f_preds = [f[vals.index(x)] for x in X[:, idx]]
    residual = residual - f_preds
    return f, f_preds, residual

# Iterative algorithm, set the tolerance here.
# Smaller tolerance values result in smaller errors.
tol = 1e-10

updates = np.inf
residual = Y - f0
residual_prev = residual
f1, f1_preds, residual = fit_main(residual, 0)
f2, f2_preds, residual = fit_main(residual, 1)
f3, f3_preds, residual = fit_main(residual, 2)
while updates > tol:
    f1_new, f1_preds_new, residual = fit_main(residual, 0)
    f2_new, f2_preds_new, residual = fit_main(residual, 1)
    f3_new, f3_preds_new, residual = fit_main(residual, 2)
    updates = np.sum(np.abs(f1_preds_new)) + np.sum(np.abs(f2_preds_new)) + np.sum(np.abs(f3_preds_new))
    f1_preds += f1_preds_new
    f2_preds += f2_preds_new
    f3_preds += f3_preds_new
    f1 += f1_new
    f2 += f2_new
    f3 += f3_new

In [5]:
f1

array([ 0.04743083, -0.03952569])

In [6]:
f2

array([ 0.04743083, -0.03952569])

In [7]:
f3

array([-6.22529644,  5.18774704])

## Fit pairs according to first "Sequential Learning" Algorithm (Simplified EBM).

In [8]:
def fit_pair(residual, idx1, idx2):
    f = np.array([
        np.array([np.mean(residual[np.logical_and(X[:, idx1] == vals[0], X[:, idx2] == vals[0])]), np.mean(residual[np.logical_and(X[:, idx1] == vals[0], X[:, idx2] == vals[1])])]),
        np.array([np.mean(residual[np.logical_and(X[:, idx1] == vals[1], X[:, idx2] == vals[0])]), np.mean(residual[np.logical_and(X[:, idx1] == vals[1], X[:, idx2] == vals[1])])])
    ])
    f_preds = [f[vals.index(xi), vals.index(xj)] for (xi, xj) in X[:, [idx1, idx2]]]
    residual = residual - f_preds
    return f, f_preds, residual

updates = np.inf
residual_prev = residual
f12, f12_preds, residual = fit_pair(residual, 0, 1)
f13, f13_preds, residual = fit_pair(residual, 0, 2)
f23, f23_preds, residual = fit_pair(residual, 1, 2)
while updates > tol:
    f12_new, f12_preds_new, residual = fit_pair(residual, 0, 1)
    f13_new, f13_preds_new, residual = fit_pair(residual, 0, 2)
    f23_new, f23_preds_new, residual = fit_pair(residual, 1, 2)
    updates = np.sum(np.abs(f12_preds_new)) + np.sum(np.abs(f13_preds_new)) + np.sum(np.abs(f23_preds_new))
    f12_preds += f12_preds_new
    f13_preds += f13_preds_new
    f23_preds += f23_preds_new
    f12 += f12_new
    f13 += f13_new
    f23 += f23_new

In [9]:
errors = residual
print(errors)

assert np.max(np.abs(errors)) < tol
print("Assertion Passed: All errors are smaller than tolerance, which was set to: {}".format(tol))

[ 1.16510250e-13 -2.45430769e-13  1.79118368e-13 -3.65613479e-13
 -2.33020501e-13  2.45430769e-13 -1.79118368e-13  1.21871160e-13
  1.16510250e-13  1.21871160e-13  1.21871160e-13]
Assertion Passed: All errors are smaller than tolerance, which was set to: 1e-10


In [10]:
f12

array([[ 4.00693341, -5.98844432],
       [-6.01040012,  2.99422216]])

In [11]:
f23

array([[-0.0329337 , -0.0548895 ],
       [ 0.04940055,  0.02744475]])

In [12]:
f13

array([[ 0.15643507, -0.23465261],
       [ 0.26072512, -0.13036256]])

In [13]:
f1

array([ 0.04743083, -0.03952569])

In [14]:
f2

array([ 0.04743083, -0.03952569])

In [15]:
f3

array([-6.22529644,  5.18774704])

In [16]:
# https://github.com/blengerich/gam_purification
from gam_purification.purify import purify
def make_density(idx1, idx2):
    densities = np.zeros((2, 2))
    for xi, xj in X[:, [idx1, idx2]]:
        densities[vals.index(xi), vals.index(xj)] += 1
    return densities


# Purify f12 into f1 and f2
intercept, m1, m2, mat, i = purify(f12.copy(), densities=make_density(0, 1))

f0 += intercept
f1 += m1
f2 += m2
f12_pure = mat

# Purify f13 into f1 and f3
intercept, m1, m2, mat, i = purify(f13.copy(), densities=make_density(0, 2))

f0 += intercept
f1 += m1
f3 += m2
f13_pure = mat

# Purify f23 into f2 and f3
intercept, m1, m2, mat, i = purify(f23.copy(), densities=make_density(1, 2))

f0 += intercept
f2 += m1
f3 += m2
f23_pure = mat

In [17]:
print("Learned pure functions:")
print("f0", f0)
print("f1", f1)
print("f2", f2)
print("f3", f3)
print("f12", f12_pure)
print("f13", f13_pure)
print("f23", f23_pure)

Learned pure functions:
f0 3.0830767232133257e-16
f1 [-1.38325958e-07  1.15271630e-07]
f2 [ 1.46134134e-07 -1.21778446e-07]
f3 [-6.00000005  5.00000004]
f12 [[ 4.00000018 -5.9999997 ]
 [-6.00000027  2.99999985]]
f13 [[-7.58562200e-08 -1.26426470e-07]
 [ 1.13784330e-07  6.32132352e-08]]
f23 [[-5.98863117e-08 -9.98106381e-08]
 [ 8.98294676e-08  4.99053191e-08]]


## Second Algorithm of "Sequential Learning"

In our context, we restrict the pairwise functions to be *pure*, so this backfitting scheme does not represent the scenario, as it learns any pairwise functions regardless of pureness.

We use pure coding to implement sequential learning.
$$
\begin{pmatrix}4&-6\\-6&3\end{pmatrix}
$$
Forms a basis of 1-dimensional space of pure functions on $(x_1, x_2)$, and also $(x_1, x_3)$ and $(x_2, x_3)$ by symmetry. In order to learn $f_{12}, f_{13}, f_{23}\in\mathcal H_2$ (pure pairwise functions), they must be a linear mutiple of these basis vectors respectively.

In [18]:
b12 = 4 * (1 - X[:, 0]) * (1 - X[:, 1]) - 6 * X[:, 0] * (1 - X[:, 1]) \
    - 6 * (1 - X[:, 0]) * X[:, 1] + 3 * X[:, 0] * X[:, 1]
b13 = 4 * (1 - X[:, 0]) * (1 - X[:, 2]) - 6 * X[:, 0] * (1 - X[:, 2]) \
    - 6 * (1 - X[:, 0]) * X[:, 2] + 3 * X[:, 0] * X[:, 2]
b23 = 4 * (1 - X[:, 1]) * (1 - X[:, 2]) - 6 * X[:, 1] * (1 - X[:, 2]) \
    - 6 * (1 - X[:, 1]) * X[:, 2] + 3 * X[:, 1] * X[:, 2]

In [19]:
residual = residual_prev

In [20]:
residual

array([ 4.13043478,  3.7173913 , -5.7826087 , -6.19565217, -5.7826087 ,
       -6.19565217,  3.30434783,  2.89130435,  4.13043478,  2.89130435,
        2.89130435])

In [21]:
M = np.c_[b12, b13, b23]
c = np.linalg.inv(M.T @ M) @ M.T @ residual.reshape(-1, 1)

In [22]:
residual = residual - (M @ c).flatten()

In [23]:
f12 = c[0] * np.array([[4, -6], [-6, 3]])
f13 = c[1] * np.array([[4, -6], [-6, 3]])
f23 = c[2] * np.array([[4, -6], [-6, 3]])

## Evaluate the residual.

In [24]:
errors = residual
print(errors)

assert np.max(np.abs(errors)) < tol
print("Assertion Passed: All errors are smaller than tolerance, which was set to: {}".format(tol))

[ 0.13340535 -0.26617287  0.20620282 -0.20616739  0.20620282 -0.20616739
  0.31869449 -0.10646773  0.13340535 -0.10646773 -0.10646773]


AssertionError: 

In [25]:
print("Learned functions:")
print("f0", f0)
print("f1", f1)
print("f2", f2)
print("f3", f3)
print("f12", f12)
print("f13", f13)
print("f23", f23)

Learned functions:
f0 3.0830767232133257e-16
f1 [-1.38325958e-07  1.15271630e-07]
f2 [ 1.46134134e-07 -1.21778446e-07]
f3 [-6.00000005  5.00000004]
f12 [[ 3.99164333 -5.98746499]
 [-5.98746499  2.9937325 ]]
f13 [[ 0.00269305 -0.00403958]
 [-0.00403958  0.00201979]]
f23 [[ 0.00269305 -0.00403958]
 [-0.00403958  0.00201979]]


In [26]:
print('\
True pure function:\n\
f0 0\n\
f1 [0, 0]\n\
f2 [0, 0]\n\
f3 [-6, 5]\n\
f12 [[4, -6],\n\
 [-6, 3]]\n\
f13 [[0, 0],\n\
 [0, 0]]\n\
f23 [[0, 0],\n\
 [0, 0]]\n\
')

True pure function:
f0 0
f1 [0, 0]
f2 [0, 0]
f3 [-6, 5]
f12 [[4, -6],
 [-6, 3]]
f13 [[0, 0],
 [0, 0]]
f23 [[0, 0],
 [0, 0]]



# Joint Learning
First, we show that learning the main with backfitting should learn the same results as using pure coding for main effects.

In [27]:
b1 = -6 * (1 - X[:, 0]) + 5 * X[:, 0]
b2 = -6 * (1 - X[:, 1]) + 5 * X[:, 1]
b3 = -6 * (1 - X[:, 2]) + 5 * X[:, 2]

In [28]:
Mm = np.c_[b1, b2, b3]
cm = np.linalg.inv(Mm.T @ Mm) @ Mm.T @ Y

In [29]:
f1_ = cm[0] * np.array([-6, 5])
f2_ = cm[1] * np.array([-6, 5])
f3_ = cm[2] * np.array([-6, 5])

In [30]:
print('f1={},f1_={}'.format(f1, f1_))
print('f2={},f2_={}'.format(f2, f2_))
print('f3={},f3_={}'.format(f3, f3_))

f1=[-1.38325958e-07  1.15271630e-07],f1_=[ 0.04743083 -0.03952569]
f2=[ 1.46134134e-07 -1.21778446e-07],f2_=[ 0.04743083 -0.03952569]
f3=[-6.00000005  5.00000004],f3_=[-6.22529644  5.18774704]


Now we do Joint learning with pure coding.

In [31]:
b12 = 4 * (1 - X[:, 0]) * (1 - X[:, 1]) - 6 * X[:, 0] * (1 - X[:, 1]) \
    - 6 * (1 - X[:, 0]) * X[:, 1] + 3 * X[:, 0] * X[:, 1]
b13 = 4 * (1 - X[:, 0]) * (1 - X[:, 2]) - 6 * X[:, 0] * (1 - X[:, 2]) \
    - 6 * (1 - X[:, 0]) * X[:, 2] + 3 * X[:, 0] * X[:, 2]
b23 = 4 * (1 - X[:, 1]) * (1 - X[:, 2]) - 6 * X[:, 1] * (1 - X[:, 2]) \
    - 6 * (1 - X[:, 1]) * X[:, 2] + 3 * X[:, 1] * X[:, 2]

In [32]:
Ma = np.c_[b1, b2, b3, b12, b13, b23]
ca = np.linalg.inv(Ma.T @ Ma) @ Ma.T @ Y

In [33]:
residuala = Y - Ma @ ca

In [34]:
errors = residuala
print(errors)

assert np.max(np.abs(errors)) < tol
print("Assertion Passed: All errors are smaller than tolerance, which was set to: {}".format(tol))

[ 2.66453526e-15  0.00000000e+00  3.55271368e-15 -2.22044605e-16
  1.77635684e-15 -5.55111512e-16  1.77635684e-15  0.00000000e+00
  2.66453526e-15  0.00000000e+00  0.00000000e+00]
Assertion Passed: All errors are smaller than tolerance, which was set to: 1e-10


In [35]:
f1_ = ca[0] * np.array([-6, 5])
f2_ = ca[1] * np.array([-6, 5])
f3_ = ca[2] * np.array([-6, 5])
f12_ = ca[3] * np.array([[4, -6], [-6, 3]])
f13_ = ca[4] * np.array([[4, -6], [-6, 3]])
f23_ = ca[5] * np.array([[4, -6], [-6, 3]])

In [36]:
print("Learned functions:")
print("f0", f0)
print("f1", f1_)
print("f2", f2_)
print("f3", f3_)
print("f12", f12_)
print("f13", f13_)
print("f23", f23_)

Learned functions:
f0 3.0830767232133257e-16
f1 [-4.99600361e-16  4.16333634e-16]
f2 [-1.66533454e-16  1.38777878e-16]
f3 [-6.  5.]
f12 [[ 4. -6.]
 [-6.  3.]]
f13 [[-5.55111512e-17  8.32667268e-17]
 [ 8.32667268e-17 -4.16333634e-17]]
f23 [[ 1.66533454e-16 -2.49800181e-16]
 [-2.49800181e-16  1.24900090e-16]]
